#!/usr/bin/env bash
# =============================================================================
# apply-github-standards.sh
# GitHub Repository Standards — generated by tech-github-repo-standards skill
#
# Context : {CONTEXT}
# Profile : {PROFILE}
# CLA/DCO : {CLA_ENABLED}
# Generated: {DATE}
#
# Usage:
#   chmod +x apply-github-standards.sh
#   ./apply-github-standards.sh
#   ./apply-github-standards.sh --dry-run
#
# Requirements:
#   - gh CLI >= 2.28 (https://cli.github.com)
#   - gh auth login completed with admin scope on all target repos
#   - Admin permissions on all target repos
# =============================================================================

set -euo pipefail

# ── Inputs ────────────────────────────────────────────────────────────────────
ORG="{ORG}"

# Space-separated repo names. Glob patterns (e.g. service-*) are expanded at
# runtime via resolve_repos(). For comma-separated lists: split and add each here.
REPOS=({REPOS})

CONTEXT="{CONTEXT}"        # internal | external
PROFILE="{PROFILE}"        # standard | collaborative | monorepo | regulated
CLA_ENABLED={CLA_ENABLED}  # true | false — adds DCO as required status check
DRY_RUN=false

# Access control — set via env vars before running.
# internal context: OWNING_TEAM is the GitHub team slug (e.g. platform-team)
# external context: MAINTAINERS is a space-separated list of GitHub usernames
OWNING_TEAM="${OWNING_TEAM:-REPLACE_WITH_TEAM_SLUG}"      # internal only
MAINTAINERS="${MAINTAINERS:-}"                             # external only

PROTECTED_BRANCHES=("main" "develop")

# ── Parse flags ───────────────────────────────────────────────────────────────
for arg in "$@"; do
  case $arg in
    --dry-run) DRY_RUN=true ;;
    *) echo "Unknown flag: $arg"; exit 1 ;;
  esac
done

# ── Guard: invalid context + profile combination ──────────────────────────────
# Endpoint: n/a — local validation only
if [[ "$CONTEXT" == "external" && "$PROFILE" == "regulated" ]]; then
  echo "ERROR: The 'regulated' profile is only available for internal context."
  echo "       Use --profile standard or --profile collaborative for external repos."
  exit 1
fi

# ── Configuration — single source of truth ────────────────────────────────────
# All profile-specific values are set here. Functions read from these variables.
# No inline profile conditionals outside this block.
case "$PROFILE" in
  standard)
    REQUIRED_APPROVALS=1
    REQUIRE_LAST_PUSH_APPROVAL=false
    REQUIRED_LINEAR_HISTORY=false
    MERGE_QUEUE_ENABLED=false
    REQUIRE_SIGNED_COMMITS=false
    REQUIRE_WEB_COMMIT_SIGNOFF=false
    ;;
  collaborative)
    REQUIRED_APPROVALS=2
    REQUIRE_LAST_PUSH_APPROVAL=true
    REQUIRED_LINEAR_HISTORY=false
    MERGE_QUEUE_ENABLED=false
    REQUIRE_SIGNED_COMMITS=false
    REQUIRE_WEB_COMMIT_SIGNOFF=false
    ;;
  monorepo)
    REQUIRED_APPROVALS=2
    REQUIRE_LAST_PUSH_APPROVAL=true
    REQUIRED_LINEAR_HISTORY=false
    MERGE_QUEUE_ENABLED=true
    REQUIRE_SIGNED_COMMITS=false
    REQUIRE_WEB_COMMIT_SIGNOFF=false
    ;;
  regulated)
    REQUIRED_APPROVALS=2
    REQUIRE_LAST_PUSH_APPROVAL=true
    REQUIRED_LINEAR_HISTORY=true
    MERGE_QUEUE_ENABLED=false
    REQUIRE_SIGNED_COMMITS=true
    REQUIRE_WEB_COMMIT_SIGNOFF=true
    ;;
  *)
    echo "ERROR: Unknown profile '$PROFILE'. Valid: standard, collaborative, monorepo, regulated"
    exit 1
    ;;
esac

# Shared across all profiles — these never vary
DISMISS_STALE_REVIEWS=true
REQUIRE_CODEOWNER_REVIEWS=true
ALLOW_FORCE_PUSHES=false
ALLOW_DELETIONS=false
REQUIRED_CONVERSATION_RESOLUTION=true

# ── Summary counters ──────────────────────────────────────────────────────────
SETTINGS_SUCCEEDED=0
SETTINGS_SKIPPED=0
SETTINGS_FAILED=0
ARTIFACTS_COMMITTED=0
declare -a MANUAL_STEPS=()

# ── Helpers ───────────────────────────────────────────────────────────────────

# run_cmd: dry-run-aware executor with pass/fail output.
# Usage: run_cmd "Description" cmd [args...]
run_cmd() {
  local description="$1"
  shift
  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [DRY-RUN] $description"
    echo "            $*"
    return 0
  fi
  echo -n "  → $description ... "
  if "$@" 2>/tmp/gh_stderr_$BASHPID; then
    echo "✓"
    (( SETTINGS_SUCCEEDED++ )) || true
  else
    local exit_code=$?
    echo "✗ (exit $exit_code)"
    sed 's/^/    /' /tmp/gh_stderr_$BASHPID >&2 || true
    (( SETTINGS_FAILED++ )) || true
    # Intentionally return 0 — failures are tracked in counters and surfaced in
    # the summary. Returning non-zero here would trigger `set -e` and abort the
    # whole script on the first failure, breaking the "continue and summarize"
    # contract. The Main loop checks SETTINGS_FAILED and exits 1 at the end.
    return 0
  fi
}

# resolve_repos: expand a glob pattern to one repo name per line.
# Non-glob names are echoed as-is.
resolve_repos() {
  local pattern="$1"
  if [[ "$pattern" == *"*"* || "$pattern" == *"?"* ]]; then
    gh repo list "$ORG" --limit 500 --json name --jq '.[].name' \
      | grep -E "^${pattern//\*/.*}$" || true
  else
    echo "$pattern"
  fi
}

# upsert_file: create or update a file in a repo via the Contents API.
# Creates the file if missing; updates (with current SHA) if it already exists.
# Idempotent — safe to re-run.
# Endpoint: PUT /repos/{owner}/{repo}/contents/{path}
upsert_file() {
  local repo="$1"
  local path="$2"
  local message="$3"
  local content_b64="$4"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [DRY-RUN] Upsert $path"
    echo "            Commit: $message"
    return 0
  fi

  echo -n "  → Commit $path ... "

  # Fetch existing file SHA (required for updates)
  local sha
  sha=$(gh api "GET /repos/$ORG/$repo/contents/$path" \
    --jq '.sha' 2>/dev/null || echo "")

  local payload
  if [[ -n "$sha" ]]; then
    payload=$(printf '{"message":"%s","content":"%s","sha":"%s"}' \
      "$message" "$content_b64" "$sha")
  else
    payload=$(printf '{"message":"%s","content":"%s"}' \
      "$message" "$content_b64")
  fi

  if echo "$payload" | gh api --method PUT \
      "/repos/$ORG/$repo/contents/$path" --input - >/dev/null 2>&1; then
    echo "✓"
    (( ARTIFACTS_COMMITTED++ )) || true
  else
    echo "✗"
    (( SETTINGS_FAILED++ )) || true
  fi
}

# ── Functions ─────────────────────────────────────────────────────────────────

# apply_repo_settings: merge policy, clean-history defaults, productivity flags.
# Endpoint: PATCH /repos/{owner}/{repo}
# Applied: all profiles, all contexts.
# Includes:
#   - Squash merge only with PR title/body as commit message (clean history)
#   - delete_branch_on_merge (auto-cleanup)
#   - allow_auto_merge (PR can be marked to merge once checks pass)
#   - has_wiki/has_projects disabled (use docs/ + Issues for code repos)
#   - web_commit_signoff_required (regulated only — closes DCO gap on web edits)
apply_repo_settings() {
  local repo="$1"
  echo "▸ Repository general settings"

  run_cmd "Squash merge only (PR title + body), auto-delete + auto-merge, disable wiki/projects" \
    gh api --method PATCH "/repos/$ORG/$repo" \
      --field allow_squash_merge=true \
      --field allow_merge_commit=false \
      --field allow_rebase_merge=false \
      --field squash_merge_commit_title=PR_TITLE \
      --field squash_merge_commit_message=PR_BODY \
      --field delete_branch_on_merge=true \
      --field allow_auto_merge=true \
      --field allow_update_branch=true \
      --field has_wiki=false \
      --field has_projects=false \
      --field web_commit_signoff_required=$REQUIRE_WEB_COMMIT_SIGNOFF
}

# apply_branch_protection: profile-scaled protection rules on each protected branch.
# Endpoints:
#   PUT  /repos/{owner}/{repo}/branches/{branch}/protection
#   POST /repos/{owner}/{repo}/branches/{branch}/protection/required_signatures  (regulated)
#   POST /repos/{owner}/{repo}/rulesets                                           (monorepo merge queue)
# Applied: all profiles — values driven by config block above
apply_branch_protection() {
  local repo="$1"
  local branch="$2"
  echo "▸ Branch protection: $branch"

  # CLA/DCO required status check
  local contexts='[]'
  if [[ "$CLA_ENABLED" == "true" ]]; then
    contexts='["DCO"]'
  fi

  # enforce_admins=true: admins are subject to all protection rules.
  # For regulated this is non-negotiable — there is no admin bypass path.
  run_cmd "Apply protection rules ($PROFILE, $REQUIRED_APPROVALS approval(s))" \
    gh api --method PUT "/repos/$ORG/$repo/branches/$branch/protection" \
      --input - <<PAYLOAD
{
  "required_status_checks": {
    "strict": true,
    "contexts": $contexts
  },
  "enforce_admins": true,
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": $DISMISS_STALE_REVIEWS,
    "require_code_owner_reviews": $REQUIRE_CODEOWNER_REVIEWS,
    "required_approving_review_count": $REQUIRED_APPROVALS,
    "require_last_push_approval": $REQUIRE_LAST_PUSH_APPROVAL
  },
  "restrictions": null,
  "required_linear_history": $REQUIRED_LINEAR_HISTORY,
  "allow_force_pushes": $ALLOW_FORCE_PUSHES,
  "allow_deletions": $ALLOW_DELETIONS,
  "block_creations": false,
  "required_conversation_resolution": $REQUIRED_CONVERSATION_RESOLUTION
}
PAYLOAD

  # Signed commits — regulated profile only
  if [[ "$REQUIRE_SIGNED_COMMITS" == "true" ]]; then
    run_cmd "Require signed commits (regulated — $branch)" \
      gh api --method POST \
        "/repos/$ORG/$repo/branches/$branch/protection/required_signatures"
  fi

  # Merge queue — monorepo profile, main branch only.
  # Classic branch protection does not support merge queues; must use rulesets API.
  if [[ "$MERGE_QUEUE_ENABLED" == "true" && "$branch" == "main" ]]; then
    run_cmd "Enable merge queue via ruleset (monorepo — main)" \
      gh api --method POST "/repos/$ORG/$repo/rulesets" \
        --input - <<MQPAYLOAD
{
  "name": "main-merge-queue",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "merge_queue",
      "parameters": {
        "check_response_timeout_minutes": 60,
        "grouping_strategy": "ALLGREEN",
        "max_entries_to_build": 5,
        "max_entries_to_merge": 5,
        "merge_method": "SQUASH",
        "min_entries_to_merge": 1,
        "min_entries_to_merge_wait_minutes": 5
      }
    }
  ]
}
MQPAYLOAD
    MANUAL_STEPS+=("Verify merge queue in repo Settings → Rules → Rulesets (monorepo profile)")
  fi
}

# apply_security_settings: Dependabot, secret scanning, push protection.
# GitHub Advanced Security attempted for regulated; skipped gracefully if unavailable.
# Endpoints:
#   PUT  /repos/{owner}/{repo}/vulnerability-alerts      — Dependabot alerts
#   PUT  /repos/{owner}/{repo}/automated-security-fixes  — Dependabot auto-PRs
#   PATCH /repos/{owner}/{repo}                          — secret scanning + push protection
# Applied: all profiles, all contexts — mandatory baseline
apply_security_settings() {
  local repo="$1"
  echo "▸ Security settings"

  run_cmd "Enable Dependabot alerts" \
    gh api --method PUT "/repos/$ORG/$repo/vulnerability-alerts"

  run_cmd "Enable Dependabot security updates (auto PRs)" \
    gh api --method PUT "/repos/$ORG/$repo/automated-security-fixes"

  run_cmd "Enable private vulnerability reporting" \
    gh api --method PUT "/repos/$ORG/$repo/private-vulnerability-reporting"

  run_cmd "Enable secret scanning and push protection" \
    gh api --method PATCH "/repos/$ORG/$repo" \
      --input - <<SECPAYLOAD
{
  "security_and_analysis": {
    "secret_scanning": {"status": "enabled"},
    "secret_scanning_push_protection": {"status": "enabled"}
  }
}
SECPAYLOAD

  # GitHub Advanced Security — regulated profile only.
  # Requires GitHub Enterprise Cloud or GHES with GHAS license.
  # Skip gracefully if license unavailable; add manual step to summary.
  if [[ "$PROFILE" == "regulated" ]]; then
    echo -n "  → Enable GitHub Advanced Security (regulated — requires Enterprise license) ... "
    if gh api --method PATCH "/repos/$ORG/$repo" \
        --input - <<GASPAYLOAD 2>/tmp/gh_ghas_$BASHPID
{
  "security_and_analysis": {
    "advanced_security": {"status": "enabled"}
  }
}
GASPAYLOAD
    then
      echo "✓"
      (( SETTINGS_SUCCEEDED++ )) || true
    else
      echo "⚠ SKIPPED"
      echo "    GitHub Advanced Security requires GHES or GitHub Enterprise Cloud."
      (( SETTINGS_SKIPPED++ )) || true
      MANUAL_STEPS+=("Enable GitHub Advanced Security in org Settings (requires Enterprise license)")
    fi
  fi
}

# apply_actions_settings: read-only defaults, GitHub-owned + verified actions only.
# Endpoints:
#   PUT /repos/{owner}/{repo}/actions/permissions                   — enable + restrict
#   PUT /repos/{owner}/{repo}/actions/permissions/selected-actions  — allowlist
#   PUT /repos/{owner}/{repo}/actions/permissions/workflow          — default permissions
# Applied: all profiles, all contexts
apply_actions_settings() {
  local repo="$1"
  echo "▸ Actions settings"

  run_cmd "Restrict to GitHub-owned and verified creator actions only" \
    gh api --method PUT "/repos/$ORG/$repo/actions/permissions" \
      --field enabled=true \
      --field allowed_actions=selected

  run_cmd "Allow GitHub-owned + verified actions; no custom patterns" \
    gh api --method PUT "/repos/$ORG/$repo/actions/permissions/selected-actions" \
      --field github_owned_allowed=true \
      --field verified_allowed=true \
      --raw-field 'patterns_allowed=[]'

  run_cmd "Set default workflow permissions: read-only, cannot approve PRs" \
    gh api --method PUT "/repos/$ORG/$repo/actions/permissions/workflow" \
      --field default_workflow_permissions=read \
      --field can_approve_pull_request_reviews=false

  if [[ "$PROFILE" == "monorepo" ]]; then
    MANUAL_STEPS+=("Monorepo: add explicit 'permissions:' blocks to each workflow file (e.g. 'contents: read') to scope Actions per workflow")
  fi
}

# apply_access: team-based (internal) or individual (external) permissions.
# Warns if direct collaborator grants exist outside the team model.
# Endpoints:
#   PUT /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}   — internal
#   PUT /repos/{owner}/{repo}/collaborators/{username}        — external
apply_access() {
  local repo="$1"
  echo "▸ Access settings"

  if [[ "$CONTEXT" == "internal" ]]; then
    if [[ "$OWNING_TEAM" == "REPLACE_WITH_TEAM_SLUG" ]]; then
      echo "  ⚠ SKIPPED: Set OWNING_TEAM env var to your GitHub team slug before running"
      (( SETTINGS_SKIPPED++ )) || true
      MANUAL_STEPS+=("Set OWNING_TEAM env var to the owning team slug, then re-run")
    else
      run_cmd "Grant @$ORG/$OWNING_TEAM admin access" \
        gh api --method PUT "/orgs/$ORG/teams/$OWNING_TEAM/repos/$ORG/$repo" \
          --field permission=admin
    fi

    # Flag direct collaborator grants outside the team model
    local direct_collabs
    direct_collabs=$(gh api "/repos/$ORG/$repo/collaborators?affiliation=direct" \
      --jq '.[].login' 2>/dev/null || true)
    if [[ -n "$direct_collabs" ]]; then
      echo "  ⚠ WARNING: Direct collaborator grants found outside the team model:"
      echo "$direct_collabs" | sed 's/^/    @/'
      MANUAL_STEPS+=("Review and remove direct collaborator grants not via teams: $(echo "$direct_collabs" | tr '\n' ' ')")
    fi

  else
    if [[ -n "$MAINTAINERS" ]]; then
      for user in $MAINTAINERS; do
        run_cmd "Grant @$user push access (external maintainer)" \
          gh api --method PUT "/repos/$ORG/$repo/collaborators/$user" \
            --field permission=push
      done
    else
      echo "  ℹ  MAINTAINERS not set — collaborator access unchanged."
      echo "     Set MAINTAINERS env var (space-separated usernames) to add maintainers."
      (( SETTINGS_SKIPPED++ )) || true
    fi
  fi
}

# commit_artifacts: upsert all standard file artifacts to the repo via the Contents API.
# Idempotent — safe to re-run. All 7 artifacts are committed regardless of profile;
# content is scaled to context × profile combination.
# Endpoint: PUT /repos/{owner}/{repo}/contents/{path}
commit_artifacts() {
  local repo="$1"
  echo "▸ Committing file artifacts"

  # ── CODEOWNERS ──────────────────────────────────────────────────────────────
  # Variant selected by context × profile. Adjust slugs/usernames before committing.
  # internal: @org/team-slug pattern   external: @username pattern

  if [[ "$CONTEXT" == "internal" && "$PROFILE" == "standard" ]]; then
    codeowners_content=$(cat <<'CODEOWNERS'
# CODEOWNERS — internal / standard
# Single owning team. All files require their approval on PRs.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

* @REPLACE_WITH_ORG/REPLACE_WITH_TEAM_SLUG
CODEOWNERS
)
  elif [[ "$CONTEXT" == "internal" && ( "$PROFILE" == "collaborative" || "$PROFILE" == "monorepo" ) ]]; then
    codeowners_content=$(cat <<'CODEOWNERS'
# CODEOWNERS — internal / collaborative | monorepo
# Path-based routing to owning teams. Adjust paths and team slugs to match your repo.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default — catches anything not matched by a more specific rule below
*                          @REPLACE_WITH_ORG/platform-team

# Application source
/src/                      @REPLACE_WITH_ORG/backend-team
/frontend/                 @REPLACE_WITH_ORG/frontend-team
/api/                      @REPLACE_WITH_ORG/backend-team

# Infrastructure and CI
/.github/                  @REPLACE_WITH_ORG/platform-team
/infra/                    @REPLACE_WITH_ORG/infra-team
/terraform/                @REPLACE_WITH_ORG/infra-team

# Documentation
/docs/                     @REPLACE_WITH_ORG/platform-team
README.md                  @REPLACE_WITH_ORG/platform-team
CODEOWNERS
)
  elif [[ "$CONTEXT" == "internal" && "$PROFILE" == "regulated" ]]; then
    codeowners_content=$(cat <<'CODEOWNERS'
# CODEOWNERS — internal / regulated
# Every path must have an explicit owner. No unowned files permitted.
# Security team is a mandatory co-reviewer on all sensitive paths.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default — both security and platform must approve unrouted files
*                          @REPLACE_WITH_ORG/security-team @REPLACE_WITH_ORG/platform-team

# Application code — security co-reviews all changes
/src/                      @REPLACE_WITH_ORG/backend-team @REPLACE_WITH_ORG/security-team
/api/                      @REPLACE_WITH_ORG/backend-team @REPLACE_WITH_ORG/security-team

# Infrastructure — dual approval required
/infra/                    @REPLACE_WITH_ORG/infra-team @REPLACE_WITH_ORG/security-team
/terraform/                @REPLACE_WITH_ORG/infra-team @REPLACE_WITH_ORG/security-team

# Configuration and secrets — security team only
/config/                   @REPLACE_WITH_ORG/security-team
**/secrets.*               @REPLACE_WITH_ORG/security-team
**/*.pem                   @REPLACE_WITH_ORG/security-team
**/*.key                   @REPLACE_WITH_ORG/security-team

# CI/CD pipelines — security review required for all changes
/.github/                  @REPLACE_WITH_ORG/platform-team @REPLACE_WITH_ORG/security-team
/.github/workflows/        @REPLACE_WITH_ORG/security-team

# Compliance artifacts
/compliance/               @REPLACE_WITH_ORG/security-team
CODEOWNERS
)
  elif [[ "$CONTEXT" == "external" && "$PROFILE" == "standard" ]]; then
    codeowners_content=$(cat <<'CODEOWNERS'
# CODEOWNERS — external / standard
# Single maintainer owns the entire repo.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

* @REPLACE_WITH_GITHUB_USERNAME
CODEOWNERS
)
  elif [[ "$CONTEXT" == "external" && "$PROFILE" == "collaborative" ]]; then
    codeowners_content=$(cat <<'CODEOWNERS'
# CODEOWNERS — external / collaborative
# Named maintainer group with path-based routing.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default — primary maintainer
*                @REPLACE_WITH_PRIMARY_MAINTAINER

# Core code — all named maintainers review
/src/            @REPLACE_WITH_PRIMARY_MAINTAINER @REPLACE_WITH_SECOND_MAINTAINER
/lib/            @REPLACE_WITH_PRIMARY_MAINTAINER @REPLACE_WITH_SECOND_MAINTAINER

# Documentation
/docs/           @REPLACE_WITH_PRIMARY_MAINTAINER
README.md        @REPLACE_WITH_PRIMARY_MAINTAINER

# CI/CD
/.github/        @REPLACE_WITH_PRIMARY_MAINTAINER
CODEOWNERS
)
  else
    # external / monorepo
    codeowners_content=$(cat <<'CODEOWNERS'
# CODEOWNERS — external / monorepo
# Granular path ownership across deployable units.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default catch-all
*                           @REPLACE_WITH_PRIMARY_MAINTAINER

# Package / service ownership — replace with your actual package names
/packages/package-a/       @REPLACE_WITH_OWNER_A
/packages/package-b/       @REPLACE_WITH_OWNER_B
/packages/package-c/       @REPLACE_WITH_OWNER_A @REPLACE_WITH_OWNER_B

# Shared and root config
/packages/shared/           @REPLACE_WITH_PRIMARY_MAINTAINER
/.github/                   @REPLACE_WITH_PRIMARY_MAINTAINER
/package.json               @REPLACE_WITH_PRIMARY_MAINTAINER
/*.json                     @REPLACE_WITH_PRIMARY_MAINTAINER
/*.yaml                     @REPLACE_WITH_PRIMARY_MAINTAINER
CODEOWNERS
)
  fi

  upsert_file "$repo" \
    ".github/CODEOWNERS" \
    "chore: apply tech-github-repo-standards CODEOWNERS ($PROFILE)" \
    "$(echo "$codeowners_content" | base64 -w 0)"

  # ── SECURITY.md ──────────────────────────────────────────────────────────────
  regulated_addendum=""
  if [[ "$PROFILE" == "regulated" ]]; then
    regulated_addendum="- NYDFS Cybersecurity Regulation (23 NYCRR 500) requirements
- Mandatory code scanning on all pull requests
- Signed commits required on all protected branches"
  fi

  security_md=$(printf '%s\n' \
"# Security Policy

## Supported Versions

| Version | Supported |
| ------- | --------- |
| latest  | ✅         |
| < 1.0   | ❌         |

## Reporting a Vulnerability

**Do not open a public GitHub issue for security vulnerabilities.**

Please report via one of the following channels:

- **GitHub private security advisory**: use the [Report a Vulnerability](../../security/advisories/new) link in the Security tab
- **Email**: security@REPLACE_WITH_SECURITY_EMAIL

### What to include

- Description of the vulnerability and affected component
- Steps to reproduce
- Potential impact assessment
- Suggested remediation (if known)

### Response timeline

- **Acknowledgement**: within 48 hours
- **Initial assessment**: within 5 business days
- **Resolution target**: within 90 days for critical issues

## Security Standards

This repository enforces:
- OWASP Top 10 guidelines
- Dependency scanning via Dependabot (automated PRs)
- Secret scanning with push protection enabled
$regulated_addendum")

  upsert_file "$repo" \
    "SECURITY.md" \
    "chore: apply tech-github-repo-standards SECURITY.md ($PROFILE)" \
    "$(echo "$security_md" | base64 -w 0)"

  # ── CONTRIBUTING.md ───────────────────────────────────────────────────────────
  contributing_md=$(cat <<CONTRIBUTING
# Contributing

Thank you for your interest in contributing.

## Getting Started

1. Fork the repository (external contributors) or clone directly (org members).
2. Create a branch from \`main\` following the naming convention below.
3. Make your changes following the conventions in this guide.
4. Open a pull request against \`main\`.

## Branch Naming

| Type | Pattern | Example |
|------|---------|---------|
| Feature | \`feat/<short-description>\` | \`feat/add-oauth-login\` |
| Bug fix | \`fix/<short-description>\` | \`fix/null-pointer-auth\` |
| Chore | \`chore/<short-description>\` | \`chore/update-deps\` |
| Docs | \`docs/<short-description>\` | \`docs/improve-readme\` |
| Hotfix | \`hotfix/<short-description>\` | \`hotfix/cve-patch\` |

Lowercase with hyphens only. No underscores, no camelCase.

## Commit Conventions

Format: \`type(scope): short description\`  ([Conventional Commits](https://www.conventionalcommits.org/))

| Type | Use for |
|------|---------|
| \`feat\` | New features |
| \`fix\` | Bug fixes |
| \`docs\` | Documentation only |
| \`refactor\` | Restructuring, no behavior change |
| \`test\` | Tests added or updated |
| \`chore\` | Maintenance, dependency updates |
| \`ci\` | CI/CD pipeline changes |
| \`perf\` | Performance improvements |

- Subject line: ≤ 50 chars, imperative mood, no trailing period
- Body: optional — explain *why*, not *what*; wrap at 72 chars
- Breaking changes: \`!\` after type + \`BREAKING CHANGE:\` in footer

## Pull Requests

- One concern per PR
- Reference related issues: \`Closes #123\`
- Fill in the PR template completely
- PRs must pass all CI checks before requesting review
- $REQUIRED_APPROVALS approval(s) required from CODEOWNERS
- Resolve all review comments before merging
- Squash merge only

## Development Setup

\`\`\`bash
git clone https://github.com/$ORG/$repo.git
cd $repo
# npm install | pip install -e ".[dev]" | go mod download | bundle install
\`\`\`

## Testing

\`\`\`bash
# npm test | pytest | go test ./... | bundle exec rspec
\`\`\`

All tests must pass. New features must include tests.

## Questions?

Open a [GitHub Discussion](../../discussions) or search existing issues first.
CONTRIBUTING
)

  upsert_file "$repo" \
    "CONTRIBUTING.md" \
    "chore: apply tech-github-repo-standards CONTRIBUTING.md ($PROFILE)" \
    "$(echo "$contributing_md" | base64 -w 0)"

  # ── Bug report issue template ──────────────────────────────────────────────
  bug_report=$(cat <<'BUGREPORT'
---
name: Bug Report
about: Report something that is not working correctly
labels: bug
assignees: ''
---

## Describe the Bug

A clear and concise description of what the bug is.

## Steps to Reproduce

1. Go to '...'
2. Click on '...'
3. Observe error

## Expected Behavior

What you expected to happen.

## Actual Behavior

What actually happened. Include error messages or stack traces.

<details>
<summary>Log output</summary>

```
Paste log output here
```

</details>

## Environment

- OS: [e.g. macOS 14, Ubuntu 22.04, Windows 11]
- Version / Branch: [e.g. v1.2.3 or main@abc1234]
- Runtime (if applicable): [e.g. Node 20, Python 3.12]

## Additional Context

Any other context relevant to this bug.
BUGREPORT
)

  upsert_file "$repo" \
    ".github/ISSUE_TEMPLATE/bug_report.md" \
    "chore: apply tech-github-repo-standards bug report template" \
    "$(echo "$bug_report" | base64 -w 0)"

  # ── Feature request issue template ────────────────────────────────────────
  feature_request=$(cat <<'FEATUREREQUEST'
---
name: Feature Request
about: Suggest a new capability or improvement
labels: enhancement
assignees: ''
---

## Problem Statement

What problem are you trying to solve?

## Proposed Solution

Describe the feature and how it would work.

## Alternatives Considered

What other approaches did you consider?

## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3

## Additional Context

Mockups, related issues, prior art, or other supporting context.
FEATUREREQUEST
)

  upsert_file "$repo" \
    ".github/ISSUE_TEMPLATE/feature_request.md" \
    "chore: apply tech-github-repo-standards feature request template" \
    "$(echo "$feature_request" | base64 -w 0)"

  # ── PR template ──────────────────────────────────────────────────────────────
  # regulated profile adds a security checklist block
  if [[ "$PROFILE" == "regulated" ]]; then
    security_checklist="
- [ ] Security impact assessed — no new data exposure or privilege escalation introduced
- [ ] No hardcoded credentials, secrets, or PII introduced
- [ ] Complies with NYDFS 23 NYCRR 500 requirements (if in scope)
- [ ] Code scanning results reviewed; all alerts resolved or documented"
  else
    security_checklist=""
  fi

  pr_template=$(printf '%s\n' \
"## Summary

Brief description of what this PR does and why.

Closes #<!-- issue number, or delete if not applicable -->

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactor (no functional changes)
- [ ] CI/CD or infrastructure change

## Changes Made

-
-
-

## Testing

- [ ] New tests added covering the changed behavior
- [ ] All existing tests pass locally
- [ ] Manually tested (steps below)

**Manual test steps:**

1.
2.

## Checklist

- [ ] Follows CONTRIBUTING.md conventions
- [ ] Self-reviewed
- [ ] Documentation updated where needed
- [ ] No new warnings or linting errors$security_checklist

## Screenshots (if applicable)

<!-- Before/after for UI changes; compliance evidence for regulated profile -->")

  upsert_file "$repo" \
    ".github/pull_request_template.md" \
    "chore: apply tech-github-repo-standards PR template ($PROFILE)" \
    "$(echo "$pr_template" | base64 -w 0)"

  # ── CodeQL workflow ────────────────────────────────────────────────────────
  # Applied: all profiles — committed file artifact
  # regulated profile adds SARIF artifact upload for audit evidence (90-day retention)
  # Docs: https://docs.github.com/en/code-security/code-scanning
  if [[ "$PROFILE" == "regulated" ]]; then
    evidence_step="
      # Upload SARIF as compliance evidence (regulated profile — 90-day retention)
      - name: Upload SARIF as compliance evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif-\${{ github.run_id }}
          path: /home/runner/work/_temp/codeql_databases/
          retention-days: 90"
  else
    evidence_step=""
  fi

  codeql_workflow=$(printf '%s\n' \
"# CodeQL Analysis — applied by tech-github-repo-standards (profile: $PROFILE)
# Docs: https://docs.github.com/en/code-security/code-scanning

name: CodeQL Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 0'   # Weekly full scan: Sunday 02:00 UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  analyze:
    name: Analyze (\${{ matrix.language }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Adjust to the languages in this repo.
        # Supported: c-cpp, csharp, go, java-kotlin, javascript-typescript,
        #            python, ruby, swift
        language: [javascript-typescript]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: \${{ matrix.language }}
          # queries: security-and-quality   # uncomment for extended query suite

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: \"/language:\${{ matrix.language }}\"
$evidence_step")

  upsert_file "$repo" \
    ".github/workflows/codeql.yml" \
    "ci: apply tech-github-repo-standards CodeQL workflow ($PROFILE)" \
    "$(echo "$codeql_workflow" | base64 -w 0)"

  # ── Dependabot version-updates config ──────────────────────────────────────
  # Enables scheduled dependency PRs alongside the security alerts/auto-fixes
  # that were enabled via the API. Detects common ecosystems; users should
  # remove unused entries or add ones for their stack.
  # Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
  dependabot_yml=$(cat <<'DEPENDABOT'
# Dependabot version updates — applied by tech-github-repo-standards
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Add or remove ecosystems below to match this repo. Common values:
#   npm, pip, gomod, maven, gradle, bundler, cargo, composer, nuget, docker
#
# `github-actions` is enabled below for every repo — workflows benefit from
# version pinning regardless of language.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    groups:
      # Batch all GitHub Actions bumps into a single weekly PR instead of
      # one PR per action. Avoids PR sprawl on fresh hardening runs where
      # several action versions are behind upstream.
      github-actions:
        patterns:
          - "*"

  # Uncomment and adjust for your primary language ecosystem:
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   groups:
  #     minor-and-patch:
  #       update-types: ["minor", "patch"]
  #   labels:
  #     - "dependencies"
DEPENDABOT
)

  upsert_file "$repo" \
    ".github/dependabot.yml" \
    "chore: apply tech-github-repo-standards Dependabot config" \
    "$(echo "$dependabot_yml" | base64 -w 0)"
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  echo "════════════════════════════════════════════════════════════════"
  echo " GitHub Repository Standards"
  echo " Context : $CONTEXT"
  echo " Profile : $PROFILE"
  echo " Org     : $ORG"
  [[ "$DRY_RUN" == "true" ]] && echo " Mode    : DRY RUN — no changes will be made"
  echo "════════════════════════════════════════════════════════════════"
  echo ""

  # Verify gh CLI is installed and authenticated
  if ! gh auth status >/dev/null 2>&1; then
    echo "ERROR: gh CLI is not authenticated. Run: gh auth login"
    exit 1
  fi

  # Resolve repos (expand glob patterns)
  local all_repos=()
  for r in "${REPOS[@]}"; do
    while IFS= read -r resolved; do
      [[ -n "$resolved" ]] && all_repos+=("$resolved")
    done < <(resolve_repos "$r")
  done

  if [[ ${#all_repos[@]} -eq 0 ]]; then
    echo "ERROR: No repos found matching: ${REPOS[*]}"
    echo "       Check REPOS and verify org access: gh repo list $ORG"
    exit 1
  fi

  echo "Repos to configure (${#all_repos[@]}):"
  printf '  %s/%s\n' "$ORG" "${all_repos[@]}"
  echo ""

  for repo in "${all_repos[@]}"; do
    echo "────────────────────────────────────────────────────────────────"
    echo " Configuring: $ORG/$repo"
    echo "────────────────────────────────────────────────────────────────"

    apply_repo_settings "$repo"
    echo ""

    for branch in "${PROTECTED_BRANCHES[@]}"; do
      if gh api "/repos/$ORG/$repo/branches/$branch" >/dev/null 2>&1; then
        apply_branch_protection "$repo" "$branch"
      else
        echo "▸ Branch '$branch' not found — skipping protection"
        echo "  Create the branch first, then re-run this script."
        (( SETTINGS_SKIPPED++ )) || true
      fi
      echo ""
    done

    apply_security_settings "$repo"
    echo ""

    apply_actions_settings "$repo"
    echo ""

    apply_access "$repo"
    echo ""

    commit_artifacts "$repo"
    echo ""
  done

  # ── Summary ───────────────────────────────────────────────────────────────
  echo "════════════════════════════════════════════════════════════════"
  echo " Summary"
  echo "════════════════════════════════════════════════════════════════"
  printf " Context applied     : %s\n" "$CONTEXT"
  printf " Profile applied     : %s\n" "$PROFILE"
  printf " Repos configured    : %s\n" "${#all_repos[@]}"
  printf " Settings succeeded  : %s\n" "$SETTINGS_SUCCEEDED"
  printf " Settings skipped    : %s\n" "$SETTINGS_SKIPPED"
  printf " Settings failed     : %s\n" "$SETTINGS_FAILED"
  printf " Artifacts committed : %s\n" "$ARTIFACTS_COMMITTED"
  echo ""

  if [[ ${#MANUAL_STEPS[@]} -gt 0 ]]; then
    echo " Manual steps required:"
    for step in "${MANUAL_STEPS[@]}"; do
      echo "   • $step"
    done
    echo ""
  fi

  if [[ "$PROFILE" == "regulated" ]]; then
    echo " Regulated profile compliance checklist:"
    echo "   □ Confirm NYDFS scope with legal/compliance"
    echo "   □ Verify GitHub Advanced Security is licensed and enabled org-wide"
    echo "   □ Enable org-level 2FA enforcement (org Settings → Authentication security)"
    echo "   □ Confirm audit log streaming is configured for the org"
    echo "   □ Archive this script and generated artifacts as configuration evidence"
    echo "   □ Schedule quarterly review of branch protection and access settings"
    echo ""
  fi

  if [[ "$SETTINGS_FAILED" -gt 0 ]]; then
    echo " ✗ $SETTINGS_FAILED setting(s) failed. Review errors above before proceeding."
    exit 1
  else
    echo " ✓ All settings applied successfully."
  fi
}

main "$@"
