#Requires -Version 5.1
# =============================================================================
# apply-github-standards.ps1
# GitHub Repository Standards — generated by tech-github-repo-standards skill
#
# Context : {CONTEXT}
# Profile : {PROFILE}
# CLA/DCO : {CLA_ENABLED}
# Generated: {DATE}
#
# Usage:
#   .\apply-github-standards.ps1
#   .\apply-github-standards.ps1 -DryRun
#
# Requirements:
#   - gh CLI >= 2.28 (https://cli.github.com)
#   - gh auth login completed with admin scope on all target repos
#   - Admin permissions on all target repos
# =============================================================================

[CmdletBinding()]
param(
    [switch]$DryRun
)

Set-StrictMode -Version Latest

# ── Inputs ────────────────────────────────────────────────────────────────────
$ORG = '{ORG}'

# Repo names. Glob patterns (e.g. service-*) are expanded at runtime via
# Resolve-Repos. For multiple repos, list them individually.
$REPOS = @('{REPOS}')

$CONTEXT = '{CONTEXT}'         # internal | external
# NOTE: $PROFILE is a PowerShell automatic variable (path to PS profile script).
#       Repo profile is stored in $RepoProfile to avoid collision.
$RepoProfile = '{PROFILE}'     # standard | collaborative | monorepo | regulated
$CLA_ENABLED = '{CLA_ENABLED}' # 'true' | 'false' — lowercase string for JSON interpolation

# Access control — set via env vars before running.
# internal: OWNING_TEAM = GitHub team slug (e.g. platform-team)
# external: MAINTAINERS = space-separated GitHub usernames
$OWNING_TEAM = if ($env:OWNING_TEAM) { $env:OWNING_TEAM } else { 'REPLACE_WITH_TEAM_SLUG' }
$MAINTAINERS  = if ($env:MAINTAINERS) {
    $env:MAINTAINERS -split '\s+' | Where-Object { $_ -ne '' }
} else { @() }

$PROTECTED_BRANCHES = @('main', 'develop')

# ── Guard: invalid context + profile combination ──────────────────────────────
if ($CONTEXT -eq 'external' -and $RepoProfile -eq 'regulated') {
    Write-Error "ERROR: The 'regulated' profile is only available for internal context.`n       Use standard or collaborative for external repos."
    exit 1
}

# ── Configuration — single source of truth ────────────────────────────────────
# All profile-specific values are set here. Functions read from these variables.
# JSON booleans stored as lowercase strings for direct interpolation into JSON bodies.
switch ($RepoProfile) {
    'standard' {
        $REQUIRED_APPROVALS            = 1
        $REQUIRE_LAST_PUSH_APPROVAL    = 'false'
        $REQUIRED_LINEAR_HISTORY       = 'false'
        $MERGE_QUEUE_ENABLED           = $false
        $REQUIRE_SIGNED_COMMITS        = $false
        $REQUIRE_WEB_COMMIT_SIGNOFF    = 'false'
    }
    'collaborative' {
        $REQUIRED_APPROVALS            = 2
        $REQUIRE_LAST_PUSH_APPROVAL    = 'true'
        $REQUIRED_LINEAR_HISTORY       = 'false'
        $MERGE_QUEUE_ENABLED           = $false
        $REQUIRE_SIGNED_COMMITS        = $false
        $REQUIRE_WEB_COMMIT_SIGNOFF    = 'false'
    }
    'monorepo' {
        $REQUIRED_APPROVALS            = 2
        $REQUIRE_LAST_PUSH_APPROVAL    = 'true'
        $REQUIRED_LINEAR_HISTORY       = 'false'
        $MERGE_QUEUE_ENABLED           = $true
        $REQUIRE_SIGNED_COMMITS        = $false
        $REQUIRE_WEB_COMMIT_SIGNOFF    = 'false'
    }
    'regulated' {
        $REQUIRED_APPROVALS            = 2
        $REQUIRE_LAST_PUSH_APPROVAL    = 'true'
        $REQUIRED_LINEAR_HISTORY       = 'true'
        $MERGE_QUEUE_ENABLED           = $false
        $REQUIRE_SIGNED_COMMITS        = $true
        $REQUIRE_WEB_COMMIT_SIGNOFF    = 'true'
    }
    default {
        Write-Error "ERROR: Unknown profile '$RepoProfile'. Valid: standard, collaborative, monorepo, regulated"
        exit 1
    }
}

# Shared across all profiles — these never vary
$DISMISS_STALE_REVIEWS           = 'true'
$REQUIRE_CODEOWNER_REVIEWS       = 'true'
$ALLOW_FORCE_PUSHES              = 'false'
$ALLOW_DELETIONS                 = 'false'
$REQUIRED_CONVERSATION_RESOLUTION = 'true'

# ── Summary counters (script scope — modified inside functions) ───────────────
$script:SettingsSucceeded  = 0
$script:SettingsSkipped    = 0
$script:SettingsFailed     = 0
$script:ArtifactsCommitted = 0
$script:ManualSteps        = [System.Collections.Generic.List[string]]::new()

# ── Helpers ───────────────────────────────────────────────────────────────────

# Invoke-Cmd: dry-run-aware executor with pass/fail output.
# Accepts a scriptblock; gh calls inside use variables from the caller's scope.
function Invoke-Cmd {
    param(
        [string]$Description,
        [scriptblock]$Block
    )
    if ($DryRun) {
        Write-Host "  [DRY-RUN] $Description"
        return
    }
    Write-Host -NoNewline "  -> $Description ... "
    $errFile = [System.IO.Path]::GetTempFileName()
    try {
        & $Block 2>$errFile | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Host 'OK'
            $script:SettingsSucceeded++
        } else {
            Write-Host "FAILED (exit $LASTEXITCODE)"
            Get-Content $errFile -ErrorAction SilentlyContinue |
                ForEach-Object { Write-Host "    $_" -ForegroundColor Red }
            $script:SettingsFailed++
        }
    } catch {
        Write-Host "FAILED ($_)"
        $script:SettingsFailed++
    } finally {
        Remove-Item $errFile -ErrorAction SilentlyContinue
    }
}

# Write-TempJson: writes a JSON string to a temp file and returns its path.
# Caller is responsible for deleting the file after use.
function Write-TempJson {
    param([string]$Json)
    $f = [System.IO.Path]::GetTempFileName()
    [System.IO.File]::WriteAllText($f, $Json, [System.Text.Encoding]::UTF8)
    return $f
}

# ConvertTo-Base64Content: UTF-8 base64 encode a string (no line breaks).
function ConvertTo-Base64Content {
    param([string]$Content)
    return [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($Content))
}

# Resolve-Repos: expand a glob pattern to a list of repo names.
# Non-glob names are returned as-is.
function Resolve-Repos {
    param([string]$Pattern)
    if ($Pattern -match '[*?]') {
        $regex = '^' + [regex]::Escape($Pattern).Replace('\*', '.*').Replace('\?', '.') + '$'
        gh repo list $ORG --limit 500 --json name --jq '.[].name' 2>$null |
            Where-Object { $_ -match $regex }
    } else {
        $Pattern
    }
}

# Invoke-UpsertFile: create or update a file via the Contents API. Idempotent.
# Endpoint: PUT /repos/{owner}/{repo}/contents/{path}
function Invoke-UpsertFile {
    param(
        [string]$Repo,
        [string]$Path,
        [string]$Message,
        [string]$Content
    )
    if ($DryRun) {
        Write-Host "  [DRY-RUN] Upsert $Path"
        Write-Host "            Commit: $Message"
        return
    }
    Write-Host -NoNewline "  -> Commit $Path ... "

    # Fetch existing file SHA (required to update an existing file)
    $sha = gh api "GET /repos/$ORG/$Repo/contents/$Path" --jq '.sha' 2>$null

    $b64 = ConvertTo-Base64Content -Content $Content
    $payloadObj = [ordered]@{ message = $Message; content = $b64 }
    if ($sha) { $payloadObj['sha'] = $sha }
    $payload = $payloadObj | ConvertTo-Json -Compress

    $tmpFile = Write-TempJson -Json $payload
    try {
        gh api --method PUT "/repos/$ORG/$Repo/contents/$Path" --input $tmpFile | Out-Null
        if ($LASTEXITCODE -eq 0) {
            Write-Host 'OK'
            $script:ArtifactsCommitted++
        } else {
            Write-Host 'FAILED'
            $script:SettingsFailed++
        }
    } finally {
        Remove-Item $tmpFile -ErrorAction SilentlyContinue
    }
}

# ── Functions ─────────────────────────────────────────────────────────────────

# Apply-RepoSettings: merge policy, clean-history defaults, productivity flags.
# Endpoint: PATCH /repos/{owner}/{repo}
# Applied: all profiles, all contexts.
# Includes:
#   - Squash merge only with PR title/body as commit message (clean history)
#   - delete_branch_on_merge (auto-cleanup)
#   - allow_auto_merge (PR can be marked to merge once checks pass)
#   - has_wiki/has_projects disabled (use docs/ + Issues for code repos)
#   - web_commit_signoff_required (regulated only — closes DCO gap on web edits)
function Apply-RepoSettings {
    param([string]$Repo)
    Write-Host '> Repository general settings'
    Invoke-Cmd 'Squash merge only (PR title + body), auto-delete + auto-merge, disable wiki/projects' {
        gh api --method PATCH "/repos/$ORG/$Repo" `
            --field allow_squash_merge=true `
            --field allow_merge_commit=false `
            --field allow_rebase_merge=false `
            --field squash_merge_commit_title=PR_TITLE `
            --field squash_merge_commit_message=PR_BODY `
            --field delete_branch_on_merge=true `
            --field allow_auto_merge=true `
            --field allow_update_branch=true `
            --field has_wiki=false `
            --field has_projects=false `
            --field web_commit_signoff_required=$REQUIRE_WEB_COMMIT_SIGNOFF
    }
}

# Apply-BranchProtection: profile-scaled protection rules on a single branch.
# Endpoints:
#   PUT  /repos/{owner}/{repo}/branches/{branch}/protection
#   POST /repos/{owner}/{repo}/branches/{branch}/protection/required_signatures  (regulated)
#   POST /repos/{owner}/{repo}/rulesets                                           (monorepo merge queue)
# Applied: all profiles — values driven by config block above
function Apply-BranchProtection {
    param([string]$Repo, [string]$Branch)
    Write-Host "> Branch protection: $Branch"

    # CLA/DCO status check context
    $contexts = if ($CLA_ENABLED) { '["DCO"]' } else { '[]' }

    # enforce_admins: true — admins are subject to all protection rules.
    # For regulated this is non-negotiable — there is no admin bypass path.
    $body = @"
{
  "required_status_checks": {
    "strict": true,
    "contexts": $contexts
  },
  "enforce_admins": true,
  "required_pull_request_reviews": {
    "dismiss_stale_reviews": $DISMISS_STALE_REVIEWS,
    "require_code_owner_reviews": $REQUIRE_CODEOWNER_REVIEWS,
    "required_approving_review_count": $REQUIRED_APPROVALS,
    "require_last_push_approval": $REQUIRE_LAST_PUSH_APPROVAL
  },
  "restrictions": null,
  "required_linear_history": $REQUIRED_LINEAR_HISTORY,
  "allow_force_pushes": $ALLOW_FORCE_PUSHES,
  "allow_deletions": $ALLOW_DELETIONS,
  "block_creations": false,
  "required_conversation_resolution": $REQUIRED_CONVERSATION_RESOLUTION
}
"@
    $tmpFile = Write-TempJson -Json $body
    try {
        Invoke-Cmd "Apply protection rules ($RepoProfile, $REQUIRED_APPROVALS approval(s))" {
            gh api --method PUT "/repos/$ORG/$Repo/branches/$Branch/protection" --input $tmpFile
        }
    } finally {
        Remove-Item $tmpFile -ErrorAction SilentlyContinue
    }

    # Signed commits — regulated profile only
    if ($REQUIRE_SIGNED_COMMITS) {
        Invoke-Cmd "Require signed commits (regulated — $Branch)" {
            gh api --method POST "/repos/$ORG/$Repo/branches/$Branch/protection/required_signatures"
        }
    }

    # Merge queue — monorepo profile, main branch only.
    # Classic branch protection does not support merge queues; must use rulesets API.
    if ($MERGE_QUEUE_ENABLED -and $Branch -eq 'main') {
        $mqBody = @'
{
  "name": "main-merge-queue",
  "target": "branch",
  "enforcement": "active",
  "conditions": {
    "ref_name": {
      "include": ["refs/heads/main"],
      "exclude": []
    }
  },
  "rules": [
    {
      "type": "merge_queue",
      "parameters": {
        "check_response_timeout_minutes": 60,
        "grouping_strategy": "ALLGREEN",
        "max_entries_to_build": 5,
        "max_entries_to_merge": 5,
        "merge_method": "SQUASH",
        "min_entries_to_merge": 1,
        "min_entries_to_merge_wait_minutes": 5
      }
    }
  ]
}
'@
        $mqFile = Write-TempJson -Json $mqBody
        try {
            Invoke-Cmd 'Enable merge queue via ruleset (monorepo — main)' {
                gh api --method POST "/repos/$ORG/$Repo/rulesets" --input $mqFile
            }
        } finally {
            Remove-Item $mqFile -ErrorAction SilentlyContinue
        }
        $script:ManualSteps.Add('Verify merge queue in repo Settings -> Rules -> Rulesets (monorepo profile)')
    }
}

# Apply-SecuritySettings: Dependabot, secret scanning, push protection.
# GitHub Advanced Security attempted for regulated; skipped gracefully if unavailable.
# Endpoints:
#   PUT  /repos/{owner}/{repo}/vulnerability-alerts
#   PUT  /repos/{owner}/{repo}/automated-security-fixes
#   PATCH /repos/{owner}/{repo}   — secret scanning + push protection
# Applied: all profiles, all contexts — mandatory baseline
function Apply-SecuritySettings {
    param([string]$Repo)
    Write-Host '> Security settings'

    Invoke-Cmd 'Enable Dependabot alerts' {
        gh api --method PUT "/repos/$ORG/$Repo/vulnerability-alerts"
    }

    Invoke-Cmd 'Enable Dependabot security updates (auto PRs)' {
        gh api --method PUT "/repos/$ORG/$Repo/automated-security-fixes"
    }

    Invoke-Cmd 'Enable private vulnerability reporting' {
        gh api --method PUT "/repos/$ORG/$Repo/private-vulnerability-reporting"
    }

    $secBody = @'
{
  "security_and_analysis": {
    "secret_scanning": {"status": "enabled"},
    "secret_scanning_push_protection": {"status": "enabled"}
  }
}
'@
    $secFile = Write-TempJson -Json $secBody
    try {
        Invoke-Cmd 'Enable secret scanning and push protection' {
            gh api --method PATCH "/repos/$ORG/$Repo" --input $secFile
        }
    } finally {
        Remove-Item $secFile -ErrorAction SilentlyContinue
    }

    # GitHub Advanced Security — regulated profile only.
    # Requires GitHub Enterprise Cloud or GHES with GHAS license.
    # Skip gracefully if unavailable; add manual step.
    if ($RepoProfile -eq 'regulated') {
        Write-Host -NoNewline '  -> Enable GitHub Advanced Security (regulated — requires Enterprise license) ... '
        $gasBody = @'
{
  "security_and_analysis": {
    "advanced_security": {"status": "enabled"}
  }
}
'@
        $gasFile = Write-TempJson -Json $gasBody
        try {
            gh api --method PATCH "/repos/$ORG/$Repo" --input $gasFile 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) {
                Write-Host 'OK'
                $script:SettingsSucceeded++
            } else {
                Write-Host 'SKIPPED'
                Write-Host '    GitHub Advanced Security requires GHES or GitHub Enterprise Cloud.' -ForegroundColor Yellow
                $script:SettingsSkipped++
                $script:ManualSteps.Add('Enable GitHub Advanced Security in org Settings (requires Enterprise license)')
            }
        } finally {
            Remove-Item $gasFile -ErrorAction SilentlyContinue
        }
    }
}

# Apply-ActionsSettings: read-only defaults, GitHub-owned + verified actions only.
# Endpoints:
#   PUT /repos/{owner}/{repo}/actions/permissions
#   PUT /repos/{owner}/{repo}/actions/permissions/selected-actions
#   PUT /repos/{owner}/{repo}/actions/permissions/workflow
# Applied: all profiles, all contexts
function Apply-ActionsSettings {
    param([string]$Repo)
    Write-Host '> Actions settings'

    Invoke-Cmd 'Restrict to GitHub-owned and verified creator actions only' {
        gh api --method PUT "/repos/$ORG/$Repo/actions/permissions" `
            --field enabled=true `
            --field allowed_actions=selected
    }

    Invoke-Cmd 'Allow GitHub-owned + verified actions; no custom patterns' {
        gh api --method PUT "/repos/$ORG/$Repo/actions/permissions/selected-actions" `
            --field github_owned_allowed=true `
            --field verified_allowed=true `
            --raw-field 'patterns_allowed=[]'
    }

    Invoke-Cmd 'Set default workflow permissions: read-only, cannot approve PRs' {
        gh api --method PUT "/repos/$ORG/$Repo/actions/permissions/workflow" `
            --field default_workflow_permissions=read `
            --field can_approve_pull_request_reviews=false
    }

    if ($RepoProfile -eq 'monorepo') {
        $script:ManualSteps.Add("Monorepo: add explicit 'permissions:' blocks to each workflow file (e.g. 'contents: read')")
    }
}

# Apply-Access: team-based (internal) or individual (external) permissions.
# Warns if direct collaborator grants exist outside the team model.
# Endpoints:
#   PUT /orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}   — internal
#   PUT /repos/{owner}/{repo}/collaborators/{username}        — external
function Apply-Access {
    param([string]$Repo)
    Write-Host '> Access settings'

    if ($CONTEXT -eq 'internal') {
        if ($OWNING_TEAM -eq 'REPLACE_WITH_TEAM_SLUG') {
            Write-Host '  SKIPPED: Set OWNING_TEAM env var to your GitHub team slug before running' -ForegroundColor Yellow
            $script:SettingsSkipped++
            $script:ManualSteps.Add('Set OWNING_TEAM env var to the owning team slug, then re-run')
        } else {
            Invoke-Cmd "Grant @$ORG/$OWNING_TEAM admin access" {
                gh api --method PUT "/orgs/$ORG/teams/$OWNING_TEAM/repos/$ORG/$Repo" `
                    --field permission=admin
            }
        }

        # Flag direct collaborator grants outside the team model
        $directCollabs = gh api "/repos/$ORG/$Repo/collaborators?affiliation=direct" `
            --jq '.[].login' 2>$null
        if ($directCollabs) {
            Write-Host '  WARNING: Direct collaborator grants found outside the team model:' -ForegroundColor Yellow
            $directCollabs | ForEach-Object { Write-Host "    @$_" -ForegroundColor Yellow }
            $script:ManualSteps.Add("Review and remove direct collaborator grants not via teams: $($directCollabs -join ' ')")
        }

    } else {
        if ($MAINTAINERS.Count -gt 0) {
            foreach ($user in $MAINTAINERS) {
                Invoke-Cmd "Grant @$user push access (external maintainer)" {
                    gh api --method PUT "/repos/$ORG/$Repo/collaborators/$user" `
                        --field permission=push
                }
            }
        } else {
            Write-Host '  INFO: MAINTAINERS not set — collaborator access unchanged.'
            Write-Host '        Set MAINTAINERS env var (space-separated usernames) to add maintainers.'
            $script:SettingsSkipped++
        }
    }
}

# Commit-Artifacts: upsert all standard file artifacts via the Contents API.
# Idempotent — safe to re-run. All 7 artifacts committed for every profile;
# content is scaled to context x profile combination.
# Endpoint: PUT /repos/{owner}/{repo}/contents/{path}
function Commit-Artifacts {
    param([string]$Repo)
    Write-Host '> Committing file artifacts'

    # ── CODEOWNERS ──────────────────────────────────────────────────────────
    # Variant selected by context x profile. Adjust slugs/usernames before committing.

    if ($CONTEXT -eq 'internal' -and $RepoProfile -eq 'standard') {
        $codeowners = @'
# CODEOWNERS — internal / standard
# Single owning team. All files require their approval on PRs.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

* @REPLACE_WITH_ORG/REPLACE_WITH_TEAM_SLUG
'@
    } elseif ($CONTEXT -eq 'internal' -and $RepoProfile -in @('collaborative', 'monorepo')) {
        $codeowners = @'
# CODEOWNERS — internal / collaborative | monorepo
# Path-based routing to owning teams. Adjust paths and team slugs to match your repo.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default — catches anything not matched by a more specific rule below
*                          @REPLACE_WITH_ORG/platform-team

# Application source
/src/                      @REPLACE_WITH_ORG/backend-team
/frontend/                 @REPLACE_WITH_ORG/frontend-team
/api/                      @REPLACE_WITH_ORG/backend-team

# Infrastructure and CI
/.github/                  @REPLACE_WITH_ORG/platform-team
/infra/                    @REPLACE_WITH_ORG/infra-team
/terraform/                @REPLACE_WITH_ORG/infra-team

# Documentation
/docs/                     @REPLACE_WITH_ORG/platform-team
README.md                  @REPLACE_WITH_ORG/platform-team
'@
    } elseif ($CONTEXT -eq 'internal' -and $RepoProfile -eq 'regulated') {
        $codeowners = @'
# CODEOWNERS — internal / regulated
# Every path must have an explicit owner. No unowned files permitted.
# Security team is a mandatory co-reviewer on all sensitive paths.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default — both security and platform must approve unrouted files
*                          @REPLACE_WITH_ORG/security-team @REPLACE_WITH_ORG/platform-team

# Application code — security co-reviews all changes
/src/                      @REPLACE_WITH_ORG/backend-team @REPLACE_WITH_ORG/security-team
/api/                      @REPLACE_WITH_ORG/backend-team @REPLACE_WITH_ORG/security-team

# Infrastructure — dual approval required
/infra/                    @REPLACE_WITH_ORG/infra-team @REPLACE_WITH_ORG/security-team
/terraform/                @REPLACE_WITH_ORG/infra-team @REPLACE_WITH_ORG/security-team

# Configuration and secrets — security team only
/config/                   @REPLACE_WITH_ORG/security-team
**/secrets.*               @REPLACE_WITH_ORG/security-team
**/*.pem                   @REPLACE_WITH_ORG/security-team
**/*.key                   @REPLACE_WITH_ORG/security-team

# CI/CD pipelines — security review required for all changes
/.github/                  @REPLACE_WITH_ORG/platform-team @REPLACE_WITH_ORG/security-team
/.github/workflows/        @REPLACE_WITH_ORG/security-team

# Compliance artifacts
/compliance/               @REPLACE_WITH_ORG/security-team
'@
    } elseif ($CONTEXT -eq 'external' -and $RepoProfile -eq 'standard') {
        $codeowners = @'
# CODEOWNERS — external / standard
# Single maintainer owns the entire repo.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

* @REPLACE_WITH_GITHUB_USERNAME
'@
    } elseif ($CONTEXT -eq 'external' -and $RepoProfile -eq 'collaborative') {
        $codeowners = @'
# CODEOWNERS — external / collaborative
# Named maintainer group with path-based routing.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default — primary maintainer
*                @REPLACE_WITH_PRIMARY_MAINTAINER

# Core code — all named maintainers review
/src/            @REPLACE_WITH_PRIMARY_MAINTAINER @REPLACE_WITH_SECOND_MAINTAINER
/lib/            @REPLACE_WITH_PRIMARY_MAINTAINER @REPLACE_WITH_SECOND_MAINTAINER

# Documentation
/docs/           @REPLACE_WITH_PRIMARY_MAINTAINER
README.md        @REPLACE_WITH_PRIMARY_MAINTAINER

# CI/CD
/.github/        @REPLACE_WITH_PRIMARY_MAINTAINER
'@
    } else {
        # external / monorepo
        $codeowners = @'
# CODEOWNERS — external / monorepo
# Granular path ownership across deployable units.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Default catch-all
*                           @REPLACE_WITH_PRIMARY_MAINTAINER

# Package / service ownership — replace with your actual package names
/packages/package-a/       @REPLACE_WITH_OWNER_A
/packages/package-b/       @REPLACE_WITH_OWNER_B
/packages/package-c/       @REPLACE_WITH_OWNER_A @REPLACE_WITH_OWNER_B

# Shared and root config
/packages/shared/           @REPLACE_WITH_PRIMARY_MAINTAINER
/.github/                   @REPLACE_WITH_PRIMARY_MAINTAINER
/package.json               @REPLACE_WITH_PRIMARY_MAINTAINER
/*.json                     @REPLACE_WITH_PRIMARY_MAINTAINER
/*.yaml                     @REPLACE_WITH_PRIMARY_MAINTAINER
'@
    }

    Invoke-UpsertFile -Repo $Repo `
        -Path '.github/CODEOWNERS' `
        -Message "chore: apply tech-github-repo-standards CODEOWNERS ($RepoProfile)" `
        -Content $codeowners

    # ── SECURITY.md ──────────────────────────────────────────────────────────
    $regulatedAddendum = if ($RepoProfile -eq 'regulated') { @'
- NYDFS Cybersecurity Regulation (23 NYCRR 500) requirements
- Mandatory code scanning on all pull requests
- Signed commits required on all protected branches
'@ } else { '' }

    $securityMd = @"
# Security Policy

## Supported Versions

| Version | Supported |
| ------- | --------- |
| latest  | Yes       |
| < 1.0   | No        |

## Reporting a Vulnerability

**Do not open a public GitHub issue for security vulnerabilities.**

Please report via one of the following channels:

- **GitHub private security advisory**: use the Report a Vulnerability link in the Security tab
- **Email**: security@REPLACE_WITH_SECURITY_EMAIL

### What to include

- Description of the vulnerability and affected component
- Steps to reproduce
- Potential impact assessment
- Suggested remediation (if known)

### Response timeline

- **Acknowledgement**: within 48 hours
- **Initial assessment**: within 5 business days
- **Resolution target**: within 90 days for critical issues

## Security Standards

This repository enforces:
- OWASP Top 10 guidelines
- Dependency scanning via Dependabot (automated PRs)
- Secret scanning with push protection enabled
$regulatedAddendum
"@

    Invoke-UpsertFile -Repo $Repo `
        -Path 'SECURITY.md' `
        -Message "chore: apply tech-github-repo-standards SECURITY.md ($RepoProfile)" `
        -Content $securityMd

    # ── CONTRIBUTING.md ───────────────────────────────────────────────────────
    $contributing = @"
# Contributing

Thank you for your interest in contributing.

## Getting Started

1. Fork the repository (external contributors) or clone directly (org members).
2. Create a branch from ``main`` following the naming convention below.
3. Make your changes following the conventions in this guide.
4. Open a pull request against ``main``.

## Branch Naming

| Type    | Pattern                        | Example                     |
|---------|--------------------------------|-----------------------------|
| Feature | ``feat/<short-description>``   | ``feat/add-oauth-login``     |
| Bug fix | ``fix/<short-description>``    | ``fix/null-pointer-auth``    |
| Chore   | ``chore/<short-description>``  | ``chore/update-deps``        |
| Docs    | ``docs/<short-description>``   | ``docs/improve-readme``      |
| Hotfix  | ``hotfix/<short-description>`` | ``hotfix/cve-patch``         |

Lowercase with hyphens only. No underscores, no camelCase.

## Commit Conventions

Format: ``type(scope): short description``  (Conventional Commits)

| Type        | Use for                            |
|-------------|------------------------------------|
| ``feat``    | New features                       |
| ``fix``     | Bug fixes                          |
| ``docs``    | Documentation only                 |
| ``refactor``| Restructuring, no behavior change  |
| ``test``    | Tests added or updated             |
| ``chore``   | Maintenance, dependency updates    |
| ``ci``      | CI/CD pipeline changes             |
| ``perf``    | Performance improvements           |

- Subject line: 50 chars max, imperative mood, no trailing period
- Body: optional — explain *why*, not *what*; wrap at 72 chars
- Breaking changes: ``!`` after type + ``BREAKING CHANGE:`` in footer

## Pull Requests

- One concern per PR
- Reference related issues: ``Closes #123``
- Fill in the PR template completely
- PRs must pass all CI checks before requesting review
- $REQUIRED_APPROVALS approval(s) required from CODEOWNERS
- Resolve all review comments before merging
- Squash merge only

## Development Setup

``````bash
git clone https://github.com/$ORG/$Repo.git
cd $Repo
# npm install | pip install -e ".[dev]" | go mod download | bundle install
``````

## Testing

``````bash
# npm test | pytest | go test ./... | bundle exec rspec
``````

All tests must pass. New features must include tests.

## Questions?

Open a GitHub Discussion or search existing issues first.
"@

    Invoke-UpsertFile -Repo $Repo `
        -Path 'CONTRIBUTING.md' `
        -Message "chore: apply tech-github-repo-standards CONTRIBUTING.md ($RepoProfile)" `
        -Content $contributing

    # ── Bug report issue template ─────────────────────────────────────────────
    $bugReport = @'
---
name: Bug Report
about: Report something that is not working correctly
labels: bug
assignees: ''
---

## Describe the Bug

A clear and concise description of what the bug is.

## Steps to Reproduce

1. Go to '...'
2. Click on '...'
3. Observe error

## Expected Behavior

What you expected to happen.

## Actual Behavior

What actually happened. Include error messages or stack traces.

<details>
<summary>Log output</summary>

```
Paste log output here
```

</details>

## Environment

- OS: [e.g. macOS 14, Ubuntu 22.04, Windows 11]
- Version / Branch: [e.g. v1.2.3 or main@abc1234]
- Runtime (if applicable): [e.g. Node 20, Python 3.12]

## Additional Context

Any other context relevant to this bug.
'@

    Invoke-UpsertFile -Repo $Repo `
        -Path '.github/ISSUE_TEMPLATE/bug_report.md' `
        -Message 'chore: apply tech-github-repo-standards bug report template' `
        -Content $bugReport

    # ── Feature request issue template ───────────────────────────────────────
    $featureRequest = @'
---
name: Feature Request
about: Suggest a new capability or improvement
labels: enhancement
assignees: ''
---

## Problem Statement

What problem are you trying to solve?

## Proposed Solution

Describe the feature and how it would work.

## Alternatives Considered

What other approaches did you consider?

## Acceptance Criteria

- [ ] Criterion 1
- [ ] Criterion 2
- [ ] Criterion 3

## Additional Context

Mockups, related issues, prior art, or other supporting context.
'@

    Invoke-UpsertFile -Repo $Repo `
        -Path '.github/ISSUE_TEMPLATE/feature_request.md' `
        -Message 'chore: apply tech-github-repo-standards feature request template' `
        -Content $featureRequest

    # ── PR template ────────────────────────────────────────────────────────────
    $securityChecklist = if ($RepoProfile -eq 'regulated') { @'

- [ ] Security impact assessed — no new data exposure or privilege escalation introduced
- [ ] No hardcoded credentials, secrets, or PII introduced
- [ ] Complies with NYDFS 23 NYCRR 500 requirements (if in scope)
- [ ] Code scanning results reviewed; all alerts resolved or documented
'@ } else { '' }

    $prTemplate = @"
## Summary

Brief description of what this PR does and why.

Closes #<!-- issue number, or delete if not applicable -->

## Type of Change

- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactor (no functional changes)
- [ ] CI/CD or infrastructure change

## Changes Made

-
-
-

## Testing

- [ ] New tests added covering the changed behavior
- [ ] All existing tests pass locally
- [ ] Manually tested (steps below)

**Manual test steps:**

1.
2.

## Checklist

- [ ] Follows CONTRIBUTING.md conventions
- [ ] Self-reviewed
- [ ] Documentation updated where needed
- [ ] No new warnings or linting errors$securityChecklist

## Screenshots (if applicable)

<!-- Before/after for UI changes; compliance evidence for regulated profile -->
"@

    Invoke-UpsertFile -Repo $Repo `
        -Path '.github/pull_request_template.md' `
        -Message "chore: apply tech-github-repo-standards PR template ($RepoProfile)" `
        -Content $prTemplate

    # ── CodeQL workflow ────────────────────────────────────────────────────────
    # Applied: all profiles — committed file artifact.
    # regulated profile adds SARIF artifact upload for audit evidence (90-day retention).
    # Docs: https://docs.github.com/en/code-security/code-scanning
    #
    # NOTE: GH Actions ${{ }} syntax is literal — no PowerShell variable interpolation.
    # Uses @'...'@ (single-quote here-string) for the static body; profile comment
    # is injected via -replace.

    $codeqlBody = @'
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * 0'   # Weekly full scan: Sunday 02:00 UTC

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  analyze:
    name: Analyze (${{ matrix.language }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # Adjust to the languages in this repo.
        # Supported: c-cpp, csharp, go, java-kotlin, javascript-typescript,
        #            python, ruby, swift
        language: [javascript-typescript]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: ${{ matrix.language }}
          # queries: security-and-quality   # uncomment for extended query suite

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        with:
          category: "/language:${{ matrix.language }}"
'@

    $evidenceStep = if ($RepoProfile -eq 'regulated') { @'

      # Upload SARIF as compliance evidence (regulated profile — 90-day retention)
      - name: Upload SARIF as compliance evidence
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: codeql-sarif-${{ github.run_id }}
          path: /home/runner/work/_temp/codeql_databases/
          retention-days: 90
'@ } else { '' }

    $codeqlWorkflow = "# CodeQL Analysis — applied by tech-github-repo-standards (profile: $RepoProfile)`n" +
                      "# Docs: https://docs.github.com/en/code-security/code-scanning`n`n" +
                      "name: CodeQL Analysis`n`n" +
                      $codeqlBody + $evidenceStep

    Invoke-UpsertFile -Repo $Repo `
        -Path '.github/workflows/codeql.yml' `
        -Message "ci: apply tech-github-repo-standards CodeQL workflow ($RepoProfile)" `
        -Content $codeqlWorkflow

    # ── Dependabot version-updates config ────────────────────────────────────
    # Enables scheduled dependency PRs alongside the security alerts/auto-fixes
    # that were enabled via the API. Detects common ecosystems; users should
    # remove unused entries or add ones for their stack.
    # Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
    $dependabotYml = @'
# Dependabot version updates — applied by tech-github-repo-standards
# Docs: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Add or remove ecosystems below to match this repo. Common values:
#   npm, pip, gomod, maven, gradle, bundler, cargo, composer, nuget, docker
#
# `github-actions` is enabled below for every repo — workflows benefit from
# version pinning regardless of language.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    groups:
      # Batch all GitHub Actions bumps into a single weekly PR instead of
      # one PR per action. Avoids PR sprawl on fresh hardening runs where
      # several action versions are behind upstream.
      github-actions:
        patterns:
          - "*"

  # Uncomment and adjust for your primary language ecosystem:
  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10
  #   groups:
  #     minor-and-patch:
  #       update-types: ["minor", "patch"]
  #   labels:
  #     - "dependencies"
'@

    Invoke-UpsertFile -Repo $Repo `
        -Path '.github/dependabot.yml' `
        -Message 'chore: apply tech-github-repo-standards Dependabot config' `
        -Content $dependabotYml
}

# ── Main ──────────────────────────────────────────────────────────────────────
function Main {
    Write-Host '================================================================'
    Write-Host ' GitHub Repository Standards'
    Write-Host " Context : $CONTEXT"
    Write-Host " Profile : $RepoProfile"
    Write-Host " Org     : $ORG"
    if ($DryRun) { Write-Host ' Mode    : DRY RUN — no changes will be made' -ForegroundColor Cyan }
    Write-Host '================================================================'
    Write-Host ''

    # Verify gh CLI is installed and authenticated
    gh auth status 2>$null | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Error 'ERROR: gh CLI is not authenticated. Run: gh auth login'
        exit 1
    }

    # Resolve repos (expand glob patterns)
    $allRepos = foreach ($r in $REPOS) {
        Resolve-Repos -Pattern $r
    }
    $allRepos = @($allRepos | Where-Object { $_ -ne '' })

    if ($allRepos.Count -eq 0) {
        Write-Error "ERROR: No repos found matching: $($REPOS -join ', ')`n       Check REPOS and verify org access: gh repo list $ORG"
        exit 1
    }

    Write-Host "Repos to configure ($($allRepos.Count)):"
    $allRepos | ForEach-Object { Write-Host "  $ORG/$_" }
    Write-Host ''

    foreach ($repo in $allRepos) {
        Write-Host '----------------------------------------------------------------'
        Write-Host " Configuring: $ORG/$repo"
        Write-Host '----------------------------------------------------------------'

        Apply-RepoSettings -Repo $repo
        Write-Host ''

        foreach ($branch in $PROTECTED_BRANCHES) {
            gh api "/repos/$ORG/$repo/branches/$branch" 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) {
                Apply-BranchProtection -Repo $repo -Branch $branch
            } else {
                Write-Host "> Branch '$branch' not found — skipping protection" -ForegroundColor Yellow
                Write-Host '  Create the branch first, then re-run this script.'
                $script:SettingsSkipped++
            }
            Write-Host ''
        }

        Apply-SecuritySettings -Repo $repo
        Write-Host ''

        Apply-ActionsSettings -Repo $repo
        Write-Host ''

        Apply-Access -Repo $repo
        Write-Host ''

        Commit-Artifacts -Repo $repo
        Write-Host ''
    }

    # ── Summary ───────────────────────────────────────────────────────────────
    Write-Host '================================================================'
    Write-Host ' Summary'
    Write-Host '================================================================'
    Write-Host " Context applied     : $CONTEXT"
    Write-Host " Profile applied     : $RepoProfile"
    Write-Host " Repos configured    : $($allRepos.Count)"
    Write-Host " Settings succeeded  : $($script:SettingsSucceeded)"
    Write-Host " Settings skipped    : $($script:SettingsSkipped)"
    Write-Host " Settings failed     : $($script:SettingsFailed)"
    Write-Host " Artifacts committed : $($script:ArtifactsCommitted)"
    Write-Host ''

    if ($script:ManualSteps.Count -gt 0) {
        Write-Host ' Manual steps required:'
        $script:ManualSteps | ForEach-Object { Write-Host "   * $_" -ForegroundColor Yellow }
        Write-Host ''
    }

    if ($RepoProfile -eq 'regulated') {
        Write-Host ' Regulated profile compliance checklist:'
        Write-Host '   [ ] Confirm NYDFS scope with legal/compliance'
        Write-Host '   [ ] Verify GitHub Advanced Security is licensed and enabled org-wide'
        Write-Host '   [ ] Enable org-level 2FA enforcement (org Settings -> Authentication security)'
        Write-Host '   [ ] Confirm audit log streaming is configured for the org'
        Write-Host '   [ ] Archive this script and generated artifacts as configuration evidence'
        Write-Host '   [ ] Schedule quarterly review of branch protection and access settings'
        Write-Host ''
    }

    if ($script:SettingsFailed -gt 0) {
        Write-Host " $($script:SettingsFailed) setting(s) failed. Review errors above before proceeding." -ForegroundColor Red
        exit 1
    } else {
        Write-Host ' All settings applied successfully.' -ForegroundColor Green
    }
}

Main
